### ISSUE TITLE
Give me a task!!

### ISSUE THREAD

**Issue by fkoerich** [bancodobrasil/stop-analyzing#11]
I'm full stack developer, ready to learn and waiting for new challenges !!

P.S: This will be my real first contribuition

**Comment by tiagostutz** [comment]
Hi @fkoerich ! 👋🏻 
Thanks a lot for your help. I'm sure we are building a great tool that will be very relevant to lots of people and businesses out there.

As you are a fullstack dev, maybe you could take the this issue https://github.com/bancodobrasil/stop-analyzing-api/issues/20? We are currently working on some migrations and data gathering now and this issue is very important for this project time.

If you want this isse, please comment o it and I'll assign that to you right away!
